spring:
    datasource:
        url: jdbc:h2:file:./demodb # jdbc:h2:mem:demodb
        username: sa
        pasword:
        driver-class-name:  org.h2.Driver # com.mysql.jdbc.Driver #
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        hibernate:
            ddl-auto: validate
        database-platform:   io.stud.forest.book_a_cinema_ticket_app.infrastructure.CustomH2Dialect # org.hibernate.dialect.H2Dialect
        properties:
            hibernate:
                globally_quoted_identifiers: true

properties:
    links:
        reservation_confirmation: "http://localhost:8080/%s/confirm"
    demo:
        initial_data: false
